
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 14 11:51:49 CST 2025
//----------------------------------------------------

package jflex_analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Metodo = 3;
  public static final int Punto = 5;
  public static final int ERROR = 9;
  public static final int Iniciar = 8;
  public static final int EOF = 0;
  public static final int Robot = 4;
  public static final int Identificador = 6;
  public static final int error = 1;
  public static final int Igual = 2;
  public static final int Numero = 7;
}

